<?php namespace ProcessWire;


class CroppableImage3 extends WireData implements Module {

    public static function getModuleInfo() {
        return array(
            'title'    => 'Croppable Image 3 (Main-Wrapper-Module)',
            'summary'  => 'Field that stores GIF, JPG, or PNG images and optionally support predefined crop functionality',
            'author'   => 'Horst Nogajski',
            'version'  => '1.1.0',
            'requires' => 'ProcessWire>=3.0.20, PHP>=5.3.8',  // , FieldtypeRangeSlider
            'installs' => 'FieltypeCroppableImage3, InputfieldCroppableImage3, ProcessCroppableImage3',
            'icon'     => 'crop'
        );
    }

//    public function __construct() {
//        parent::__construct();
//    }

    public function init() {
        parent::init();
    }

}
